{
    env: {
        esbuild_options: "echo --bundle --sourcemap --platform=node --format=esm --external:@j-cake/jcake-utils",
    },
    targets: {
        'test/*.js': {
            dependencies: ['src/\\1.ts'],
            run: "esbuild \"src/$target_1.ts\" \"--outfile=test/$target_1.js\" $esbuild_options",
        }
    }
}
