name: Publish package to GitHub Packages
on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
      - run: npm run build
      - run: |
          echo "
            //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN}}
            @J-Cake:registry=https://npm.pkg.github.com
            always-auth=true" > $HOME/.npmrc; cat ~/.npmrc
            
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
